### ISSUE TITLE
Create a for loop start from 1 to 100

### ISSUE THREAD

**Issue by B3ns44d** [tijaniabdellatif/collaborating#2]
@tijaniabdellatif  can you add a for loop ?

**Comment by tijaniabdellatif** [comment]
i don't understand your request @B3ns44d

**Comment by B3ns44d** [comment]
dir wahd for loop wsafi

**Comment by B3ns44d** [comment]
create a new file name forloop.js

**Comment by B3ns44d** [comment]
work done
